server:
  port: 9095
socketio:
  server:
    host: 192.168.1.21
    port: 9094

####

##wss.server.port=8081
##wss.server.host=localhost

spring:
  datasource:
    url: jdbc:mysql://192.168.1.31:3306/nettysocketio
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
#    hibernate:
#      ddl-auto: update
#      naming:
#        strategy: org.hibernate.cfg.ImprovedNamingStrategy
